### PR TITLE
Add multiple languages support for course checklists page

### PR DESCRIPTION
**Pull request by amitvadhel**
I tried to apply translation on checklist page, but sadly translation wasn't reflected.

If I'm not wrong there was static language (`locale = 'en'`) for courseHealthCheckIndex and courseOutlineHealthCheckIndex, I used `./utils/i18n/loadI18nDomData` to make it dynamic :)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @amitvadhel! I've created [OSPR-4489](https://openedx.atlassian.net/browse/OSPR-4489) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@amitvadhel Thank you for your contribution. Please let me know once all tests are green.

**Comment by amitvadhel** [comment]
@natabene All tests are green!

**Comment by amitvadhel** [comment]
@natabene, any updates on the review?

**Comment by natabene** [comment]
@amitvadhel We have not had a chance to review yet. Please note it may take some days/weeks, but the reviewer will post here once they are available.

**Comment by natabene** [comment]
@nasthagiri Is this something you can review?

**Comment by nasthagiri** [comment]
@fysheets Would you be able to review this?  You have more context on this code than I.

**Comment by fysheets** [comment]
Can you please rebase the branch, and I can merge once that's all set.

**Comment by amitvadhel** [comment]
Done with rebasing.

**Comment by edx-webhook** [comment]
@amitvadhel 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/studio-frontend&entry.867055334=https://github.com/edx/studio-frontend/pull/285&entry.1484655318=https://github.com/amitvadhel&entry.752974735=2020-05-07+14:53&entry.1917517419=2020-05-27+12:07&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
