### PR TITLE
Revert remove enable_quality PR

### PR DESCRIPTION
**Pull request by asadazam93**
### Description
Revert https://github.com/edx/studio-frontend/pull/251/files to re use the enable_quality feature for courses
`

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] @fysheets  
- [x] @awaisdar001 

### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by asadazam93** [comment]
@fysheets I have created the platform PR as well. Do we have to merge the studio-front-end PR first in order to test this PR?

**Comment by fysheets** [comment]
@asadazam93 I will take a look at this today, I can pull both branches locally and use the `private.py` method in platform to do sanity test locally. You can set up studio-frontend in your local devstack with the `private.py` settings change to test locally as well.

**Comment by fysheets** [comment]
Upon testing this, I see that the HTTP request to get the quality data is still getting fetched even when the display for the quality API is hidden (when the waffle hides quality).  I will attach screenshots and notes in the ticket.

**Comment by asadazam93** [comment]
@fysheets The travis tests have passed. Can you please review the PR?

**Comment by asadazam93** [comment]
@fysheets I have rebased and changed the commit message.

**Comment by fysheets** [comment]
Unfortunately you can't have capitals in the commit message so the capital T should be a lowercase t. 

Also revert() is not a valid type: https://github.com/angular/angular.js/blob/62e2ec18e65f15db4f52bb9f695a92799c58b5f1/DEVELOPERS.md#type There is documentation on how to capture a revert as well, however as this isn't a clean revert (there was additional logic added here / not calling the API etc) I would recommend using the fix() type here as we're reintroducing a fix option for courses. Also this type will definitely release a patch version bump automatically that we can use to update platform.

**Pull request merged**
